Zenoh: stabilize rust coverage builds (#15781)
There is a failure in the coverage log

https://oss-fuzz-build-logs.storage.googleapis.com/log-c8e05841-61c3-4a6d-9ebe-7b049feb8d0e.txt

```
Step #5: Already have image (with digest): gcr.io/oss-fuzz-base/base-runner
Step #5: warning [/corpus/endpoint_from_str.zip]:  zipfile is empty
Step #5: Failed to unpack the corpus for endpoint_from_str. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: warning [/corpus/network_message.zip]:  zipfile is empty
Step #5: Failed to unpack the corpus for network_message. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: warning [/corpus/scouting_message.zip]:  zipfile is empty
Step #5: Failed to unpack the corpus for scouting_message. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: warning [/corpus/transport_message.zip]:  zipfile is empty
Step #5: Failed to unpack the corpus for transport_message. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.
Step #5: ********************************************************************************
Step #5: Code coverage report generation failed.
Step #5: To reproduce, run:
Step #5: python infra/helper.py build_image zenoh
Step #5: python infra/helper.py build_fuzzers --sanitizer coverage zenoh
Step #5: python infra/helper.py coverage zenoh
Step #5: ********************************************************************************
Finished Step #5
ERROR
ERROR: build step 5 "gcr.io/oss-fuzz-base/base-runner" failed: step exited with non-zero status: 1
```

Refer to
[wasmi](https://github.com/google/oss-fuzz/tree/master/projects/wasmi),
we should make some updates, including `coverage_extra_args` in
`project.yaml` and `nightly="+$RUSTUP_TOOLCHAIN"` in `build.sh`

Signed-off-by: ChenYing Kuo <evshary@gmail.com>