[icu] Fix broken build due to incomplete result type.
Got broken after http://bugs.icu-project.org/trac/changeset/39684/trunk/icu4c/source/common/unicode/locid.h

With error like the one below:
<...>
In file included from /src/break_iterator_fuzzer.cc:8:
/src/fuzzer_utils.h:37:20: error: incomplete result type 'icu::UnicodeString' in function definition
icu::UnicodeString UnicodeStringFromUtf8(const uint8_t* data, size_t size) {
                   ^
/src/icu/source/common/unicode/locid.h:50:7: note: forward declaration of 'icu_59::UnicodeString'
class UnicodeString;
      ^
<...>