Revert "infra: bump indexer to llvm-21" (#13901)
Reverts google/oss-fuzz#13848

Unfortunately, this breaks the indexer for many projects that are still
building on clang 18 with errors like:

```
Step #23: fatal error: too many errors emitted, stopping now [-ferror-limit=]
Step #23:       |                                         ^~~~~~~~~~~~
Step #23:   422 |     return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
Step #23: /usr/local/lib/clang/18/include/mmintrin.h:422:41: error: cannot initialize a parameter of type 'unsigned int' with an rvalue of type '__v8qi' (vector of 8 'char' values)
Step #23:       |                   ^~~~~~~~~~~~~~~~~~~~~
Step #23:   422 |     return (__m64)__builtin_ia32_paddsb((__v8qi)__m1, (__v8qi)__m2);
Step #23: /usr/local/lib/clang/18/include/mmintrin.h:422:19: error: use of undeclared identifier '__builtin_ia32_paddsb'; did you mean '__builtin_ia32_kaddsi'?
Step #23:       |                   ^~~~~~~~~~~~~~~~~~~~
Step #23:   400 |     return (__m64)__builtin_ia32_paddd((__v2si)__m1, (__v2si)__m2);
Step #23: /usr/local/lib/clang/18/include/mmintrin.h:400:19: error: use of undeclared identifier '__builtin_ia32_paddd'
Step #23:       |                   ^~~~~~~~~~~~~~~~~~~~
Step #23:   379 |     return (__m64)__builtin_ia32_paddw((__v4hi)__m1, (__v4hi)__m2);
Step #23: /usr/local/lib/clang/18/include/mmintrin.h:379:19: error: use of undeclared identifier '__builtin_ia32_paddw'
Step #23:       |                   ^~~~~~~~~~~~~~~~~~~~
Step #23:   358 |     return (__m64)__builtin_ia32_paddb((__v8qi)__m1, (__v8qi)__m2);
Step #23: /usr/local/lib/clang/18/include/mmintrin.h:358:19: error: use of undeclared identifier '__builtin_ia32_paddb'
```