Revert "wireshark: fix build (#15123)"
This reverts commit 2c0b1fae85e3eb57a8a47273dce200bf8d238353.

An upstream fix for this was committed soon afterwards, that
checks for the GLib version. This fix fails when compiling
on Ubuntu 24.04, which has newer GLib, because the
G_REGEX_MATCH_DEFAULT is defined as part of an enum:

        /usr/include/glib-2.0/glib/gregex.h:398:3: error: expected identifier
          398 |   G_REGEX_MATCH_DEFAULT GLIB_AVAILABLE_ENUMERATOR_IN_2_74 = 0,
              |   ^
        <command line>:8:31: note: expanded from macro 'G_REGEX_MATCH_DEFAULT'
            8 | #define G_REGEX_MATCH_DEFAULT 0
              |                               ^
        1 error generated.

Signed-off-by: John Thacker <johnthacker@gmail.com>