haproxy: Add missing includes (#11757)
Needed for clang-18:

```
fuzz_cfg_parser.c:29:41: error: call to undeclared function 'getpid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   29 |         sprintf(filename, "/tmp/libfuzzer.%d", getpid());
      |                                                ^
fuzz_cfg_parser.c:38:2: error: call to undeclared function 'readcfgfile'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   38 |         readcfgfile(filename);
      |         ^
fuzz_cfg_parser.c:40:2: error: call to undeclared function 'unlink'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   40 |         unlink(filename);
      |         ^
3 errors generated.
ERROR:__main__:Building fuzzers failed.

Co-authored-by: MarcoFalke <6399679+MarcoFalke@users.noreply.github.com>