[libvpx] Disable encoders in libvpx (#2126)
Disable encoders while building libvpx
Current tools_common.c requires y4minput.c when encoders are enabled.
Instead of adding y4minput while linking fuzzer binary, encoders are
disabled during libvpx configure.
This resolves undefined reference to functions in y4minput.c