tomcat: fix broken build (#16127)
The build successfully compiled several fuzzers but failed on
`WsPingPongFuzzer.java`. The fix replaced
`ctx.addServletMappingDecoded("/", "default");` with
`ctx.addServletMapping("/", "default");` in `WsPingPongFuzzer.java`. The
build log indicates a compilation error because
`addServletMappingDecoded` cannot be found.

> error: cannot find symbol 
> ctx.addServletMappingDecoded("/", "default");

Signed-off-by: xingyaner <longfor2025@gmail.com>