apache-httpd: Add missing includes (#11736)
This is needed for compilers after clang-16. Otherwise, there are
errors, such as:

```
/src/fuzz_request.c:59:3: error: call to undeclared function 'ap_hook_http_scheme'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   59 |   ap_hook_http_scheme(http_scheme2, NULL, NULL, APR_HOOK_REALLY_LAST);
      |   ^
/src/fuzz_request.c:92:5: error: call to undeclared function 'ap_method_registry_init'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   92 |     ap_method_registry_init(conn.pool);
      |     ^

---------

Co-authored-by: MarcoFalke <6399679+MarcoFalke@users.noreply.github.com>