[qt] Build from the dev branch
Removing i386 because it fails with:

../bootstrap/libBootstrap.a(qdatetime.cpp.o): In function `qMulOverflow<long long>':
/work/qtbase/include/QtCore/../../../../src/qt/qtbase/src/corelib/global/qnumeric.h:122: undefined reference to `__mulodi4'