[wireshark] disable bulding fuzzshark
I added auto-building fuzzshark to wireshark, to avoid oss-fuzz build being broken,
but it actually broke the build:

Step #3:   CC       tools/oss-fuzzshark/fuzzshark-fuzzshark.o
Step #3:   CC       tools/oss-fuzzshark/fuzzshark-StandaloneFuzzTargetMain.o
Step #3:   CCLD     fuzzshark
Step #3: /usr/bin/ld: epan/.libs/libwireshark.a(packet-ipsec.o): undefined reference to symbol 'gpg_strerror@@GPG_ERROR_1.0'
Step #3: //lib/x86_64-linux-gnu/libgpg-error.so.0: error adding symbols: DSO missing from command line
Step #3: clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
Step #3: Makefile:1821: recipe for target 'fuzzshark' failed