quickjs: Add missing include to fuzz_eval.c (#11748)
This is required for modern compilers to be able to compile it.
Otherwise:

```
fuzz_eval.c:61:9: error: call to undeclared library function 'memcpy' with type 'void *(void *, const void *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   61 |         memcpy(NullTerminatedData, Data, Size);
      |         ^
fuzz_eval.c:61:9: note: include the header <string.h> or explicitly provide a declaration for 'memcpy'
1 error generated.
ERROR:__main__:Building fuzzers failed.

Co-authored-by: MarcoFalke <6399679+MarcoFalke@users.noreply.github.com>